spring.application.name=projeto-irriga

spring.datasource.url= ${DATABASE_URL}
spring.datasource.username= ${DATABASE_USER}
spring.datasource.password= ${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Arduino BLE
ble.device-address=D8:A9:8B:7A:49:EA
ble.adapter=hci0

# Serviço GATT FFE0
ble.service-uuid=0000ffe0-0000-1000-8000-00805f9b34fb

# Característica GATT FFE1
ble.characteristic-uuid=0000ffe1-0000-1000-8000-00805f9b34fb

# Scan
ble.scan-timeout-ms=10000

# Timeout da resposta
ble.response-timeout-ms=5000