spring.application.name=projeto-irriga

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

ble.device-name=ArduinoBLE-JSON
ble.adapter=hci0
ble.service-uuid=12345678-1234-5678-1234-56789abcdef0
ble.tx-characteristic-uuid=12345678-1234-5678-1234-56789abcdef1
ble.rx-characteristic-uuid=12345678-1234-5678-1234-56789abcdef2
ble.scan-timeout-ms=10000